services:
  demo-provider:
    image: ghcr.io/paul2708/cs2-stats-demo-provider:main
    restart: always
    env_file:
      - .env

  discord-bot:
    image: ghcr.io/paul2708/cs2-stats-discord-bot:main
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env

  postgres:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: