package de.paul2708.cs2stats.discord;

import net.dv8tion.jda.api.entities.emoji.Emoji;
import net.dv8tion.jda.api.events.interaction.command.SlashCommandInteractionEvent;
import net.dv8tion.jda.api.hooks.ListenerAdapter;
import net.dv8tion.jda.api.interactions.components.buttons.Button;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class InfoCommand extends ListenerAdapter {

    private static final Logger logger = LoggerFactory.getLogger(InfoCommand.class);

    @Override
    public void onSlashCommandInteraction(SlashCommandInteractionEvent event) {
        if (event.getName().equals("info")) {
            logger.info("Handle /info command issued by {}", event.getUser().getName());

            // Send info
            String message = """
                    **👋 Hello %s!**
                    
                    Here’s what we need from you to proceed with linking your CS2 account:
                    
                    🔹 **Steam ID** – Your unique Steam ID associated with your Steam account (e.g., `76561198106142637`)
                    🔹 **Share Code** – Code that references the game that is furthest back (e.g., `CSGO-XXXXX-XXXXX-XXXXX-XXXXX-XXXXX`)
                    🔹 **Authentication Code** – Generated by CS2 used to fetch your newest share codes (e.g., `XXXX-XXXX-XXXX`)
                    
                    Run the command `/register` with the required information.
                    
                    You can access and generate the required information by clicking the buttons below:
                    
                    """.formatted(event.getUser().getAsMention());

            Button steamIdButton = Button.link("https://steamcommunity.com/my",
                            "Get my Steam ID (see ID in URL)")
                    .withEmoji(Emoji.fromUnicode("\uD83D\uDD17"));
            Button shareCodeButton = Button.link("https://help.steampowered.com/en/wizard/HelpWithGameIssue/?appid=730&issueid=128&ref=google.com",
                            "Generate Auth and Share Code")
                    .withEmoji(Emoji.fromUnicode("\uD83D\uDCC4"));

            event.reply(message)
                    .addActionRow(steamIdButton, shareCodeButton)
                    .setEphemeral(true)
                    .queue();
        }
    }
}
