package de.paul2708.cs2stats.discord;

import de.paul2708.cs2stats.entity.SteamUser;
import de.paul2708.cs2stats.repository.SteamUserRepository;
import de.paul2708.cs2stats.service.MatchService;
import de.paul2708.cs2stats.steam.ShareCode;
import net.dv8tion.jda.api.entities.emoji.Emoji;
import net.dv8tion.jda.api.events.interaction.command.SlashCommandInteractionEvent;
import net.dv8tion.jda.api.hooks.ListenerAdapter;
import net.dv8tion.jda.api.interactions.commands.OptionMapping;
import net.dv8tion.jda.api.interactions.components.buttons.Button;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class RegisterCommand extends ListenerAdapter {

    private static final Logger logger = LoggerFactory.getLogger(RegisterCommand.class);

    private final SteamUserRepository steamUserRepository;
    private final MatchService matchService;

    public RegisterCommand(SteamUserRepository steamUserRepository, MatchService matchService) {
        this.steamUserRepository = steamUserRepository;
        this.matchService = matchService;
    }

    @Override
    public void onSlashCommandInteraction(SlashCommandInteractionEvent event) {
        if (event.getName().equals("register")) {
            logger.info("Handle /register command issued by {}", event.getUser().getName());

            OptionMapping steamIdOption = event.getOption("steamid");
            OptionMapping shareCodeOption = event.getOption("sharecode");
            OptionMapping authenticationCodeOption = event.getOption("authenticationcode");

            if (steamIdOption != null && shareCodeOption != null && authenticationCodeOption != null) {
                String steamId = steamIdOption.getAsString();
                String shareCode = shareCodeOption.getAsString();
                String authenticationCode = authenticationCodeOption.getAsString();

                // Register
                ShareCode parsedShareCode;
                try {
                    parsedShareCode = ShareCode.fromCode(shareCode);
                } catch (IllegalArgumentException e) {
                    event.reply("Illegal share code. Did you copy the right one, starting with CSGO-?")
                            .setEphemeral(true)
                            .queue();
                    return;
                }

                SteamUser steamUser = new SteamUser(steamId, parsedShareCode, authenticationCode, parsedShareCode);
                steamUserRepository.create(steamUser);

                matchService.fetchLatestMatches(steamUser);

                event.reply("Registered :) We are fetching your previous games. This may take a while.")
                        .setEphemeral(true)
                        .queue();

                logger.info("Discord user {} registered their steam account with Steam ID {}",
                        event.getUser().getName(), steamUser.steamId());
            } else {
                // Send info
                String message = """
                        **👋 Hello %s!**
                        
                        Here’s what we need from you to proceed with linking your CS:GO account:
                        
                        🔹 **Steam ID** – Your unique Steam ID associated with your Steam account (e.g., `76561198106142637`)
                        🔹 **Share Code** – Code that references the game that is furthest back (e.g., `CSGO-XXXXX-XXXXX-XXXXX-XXXXX-XXXXX`)
                        🔹 **Authentication Code** – Generated by CS2 used to fetch your newest share codes (e.g., `XXXX-XXXX-XXXX`)
                        
                        Run the command `/register` with the required information.
                        
                        You can access and generate the required information by clicking the buttons below:
                        
                        """.formatted(event.getUser().getAsMention());

                Button steamIdButton = Button.link("https://steamcommunity.com/my",
                                "Get my Steam ID (see ID in URL)")
                        .withEmoji(Emoji.fromUnicode("\uD83D\uDD17"));
                Button shareCodeButton = Button.link("https://help.steampowered.com/en/wizard/HelpWithGameIssue/?appid=730&issueid=128&ref=google.com",
                                "Generate Auth and Share Code")
                        .withEmoji(Emoji.fromUnicode("\uD83D\uDCC4"));

                event.reply(message)
                        .addActionRow(steamIdButton, shareCodeButton)
                        .setEphemeral(true)
                        .queue();
            }
        }
    }
}
